//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPOLab.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPOLab.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string FilterPage_Apply {
            get {
                return ResourceManager.GetString("FilterPage_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string FilterPage_Clear {
            get {
                return ResourceManager.GetString("FilterPage_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Image.
        /// </summary>
        internal static string FilterPage_HasImage {
            get {
                return ResourceManager.GetString("FilterPage_HasImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Video.
        /// </summary>
        internal static string FilterPage_HasVideo {
            get {
                return ResourceManager.GetString("FilterPage_HasVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FilterPage_Name {
            get {
                return ResourceManager.GetString("FilterPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        internal static string FilterPage_Producer {
            get {
                return ResourceManager.GetString("FilterPage_Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string FilterPage_Rating {
            get {
                return ResourceManager.GetString("FilterPage_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterPage_Title {
            get {
                return ResourceManager.GetString("FilterPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string FilterPage_Year {
            get {
                return ResourceManager.GetString("FilterPage_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string MainPage_Filter {
            get {
                return ResourceManager.GetString("MainPage_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Film.
        /// </summary>
        internal static string MainPage_NewFilm {
            get {
                return ResourceManager.GetString("MainPage_NewFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainPage_Settings {
            get {
                return ResourceManager.GetString("MainPage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films.
        /// </summary>
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Film.
        /// </summary>
        internal static string NewPage_Create {
            get {
                return ResourceManager.GetString("NewPage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string NewPage_Description {
            get {
                return ResourceManager.GetString("NewPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string NewPage_Genre {
            get {
                return ResourceManager.GetString("NewPage_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        internal static string NewPage_Image {
            get {
                return ResourceManager.GetString("NewPage_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string NewPage_Language {
            get {
                return ResourceManager.GetString("NewPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NewPage_Name {
            get {
                return ResourceManager.GetString("NewPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        internal static string NewPage_Producer {
            get {
                return ResourceManager.GetString("NewPage_Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string NewPage_Rating {
            get {
                return ResourceManager.GetString("NewPage_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Film.
        /// </summary>
        internal static string NewPage_Title {
            get {
                return ResourceManager.GetString("NewPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Video.
        /// </summary>
        internal static string NewPage_Video {
            get {
                return ResourceManager.GetString("NewPage_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string NewPage_Year {
            get {
                return ResourceManager.GetString("NewPage_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string SettingsPage_DarkMode {
            get {
                return ResourceManager.GetString("SettingsPage_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Name.
        /// </summary>
        internal static string SettingsPage_FontName {
            get {
                return ResourceManager.GetString("SettingsPage_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string SettingsPage_FontSize {
            get {
                return ResourceManager.GetString("SettingsPage_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsPage_Language {
            get {
                return ResourceManager.GetString("SettingsPage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsPage_Save {
            get {
                return ResourceManager.GetString("SettingsPage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
    }
}
